spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawl_data?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root


mybatis:
  type-aliases-package: com.wyl.mybatis.entity
  mapper-locations: classpath:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
#  params: pageNum=currentPage;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero

