server:
  port: 8111

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      hikari:
        max-pool-size: 60
        min-idle: 10
        connection-timeout: 60000
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-test-query: select 1
        is-auto-commit: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: 123456
          type: com.zaxxer.hikari.HikariDataSource


  redis:
    host: 192.168.0.35
    port: 36379
    database: 2
    password: 123456
    lettuce:
      pool:
        max-active: 32
        min-idle: 8
        max-idle: 16


init:
  enabled: false
